---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: http_server
  namespace: default
  labels:
    app: http_server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http_server
  template:
    metadata:
      labels:
        app: http_server
    spec:
      containers:
        - name: http_server
          image: "maxmills/http_server:latest"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: http_server
spec:
  type: NodePort
  selector:
    app: http_server
  ports:
    - port: 8080
      targetPort: 80
