---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: http-server
  namespace: default
  labels:
    app: http-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-server
  template:
    metadata:
      labels:
        app: http-server
    spec:
      containers:
        - name: http-server
          image: "maxmills/http-server:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 3
            httpGet:
              path: /healthcheck
              port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: http-server
spec:
  type: NodePort
  selector:
    app: http-server
  ports:
    - port: 8080
      targetPort: 80
