name: Deploy to K8

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.1.0

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_NAME: your-docker-username/http_server
        run: |
          docker build -t $IMAGE_NAME .
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push $IMAGE_NAME

  # deploy:
  #   runs-on: ubuntu-latest

  #   needs: build

  #   steps:
  #     - name: Install kubectl
  #       uses: azure/setup-kubectl@v1
  #       with:
  #         install-kubectl: true

  #     - name: Set up Helm
  #       uses: azure/setup-helm@v2

  #     - name: Deploy to Kubernetes
  #       env:
  #         KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
  #       run: |
  #         echo "$KUBE_CONFIG_DATA" | base64 --decode > kubeconfig.yml
  #         kubectl config use-context your-cluster-name
  #         helm upgrade --install your-release-name ./path/to/helm/chart
