name: Deploy to K8

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "3.1"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            maxmills/http-server:latest
            maxmills/http-server:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  test:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start minikube
        uses: medyagh/setup-minikube@master
        with:
          addons: metrics-server

      - name: Build image
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker build -f ./Dockerfile -t maxmills/http-server:latest .
          echo -n 'verifying image built: '
          docker images

      - name: Deploy to Minikube
        run: helm install http-server ./helm
        #run: kubectl apply -f deployment.yaml

      - name: Test services
        run: |
          until minikube service http-server --url; do
            echo "waiting for service to be ready"
            sleep 1
          done

          echo "HELM TEST"
          helm test http-server
          
          sleep 120
          echo "KUBECTL TOP NODES"
          kubectl top nodes
          echo "DESCRIBE SERVICE"
          kubectl describe service/http-server
          
#          curl $(minikube service http-server --url)
#          curl $(minikube service http-server --url)/healthcheck
#          if [ "$(curl $(minikube service http-server --url))" != "Well, hello there!" ] || [ "$(curl $(minikube service http-server --url)/healthcheck)" != "OK" ]; then
#            echo "Service not working"
#            exit 1
#          else
#            echo "Service is working"
#          fi
