name: Deploy to K8

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "3.1"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: maxmills/http_server:latest

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Install kubectl
        uses: azure/setup-kubectl@v1
        with:
          install-kubectl: true

      - name: Deploy to Minikube
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)

      #- name: Set up Helm
      #  uses: azure/setup-helm@v2

#     - name: Deploy to Kubernetes
#       env:
#         KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
#       run: |
#         echo "$KUBE_CONFIG_DATA" | base64 --decode > kubeconfig.yml
#         kubectl config use-context your-cluster-name
#         helm upgrade --install your-release-name ./path/to/helm/chart

#
