name: Deploy to K8

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "3.1"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            maxmills/http-server:latest
            maxmills/http-server:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  test:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start minikube
        uses: medyagh/setup-minikube@master
        with:
          addons: metrics-server
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Pull image
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker pull maxmills/http-server:latest
          echo -n 'verifying image pulled: '
          docker images

      - name: Deploy to Minikube
        run: helm install http-server ./helm

      - name: Test services
        run: |
          until minikube service http-server --url; do
            echo "waiting for service to be ready"
            sleep 1
          done

          sleep 120
          echo "KUBECTL TOP NODES"
          kubectl top nodes
          echo "DESCRIBE SERVICE"
          kubectl describe service/http-server